--select * from HRMS_EmailTemplates where EmailTemplateId=66
--Update HRMS_EmailTemplates
--set EmailBody='Hi,<br><br>This is a reminder that the allocation for ##employee name## on the project <br> ##project name## is ending on ##allocation end date##.<br>In case you need to extend the allocation, kindly send an extension request to RMG through Old Vibrant web Helpdesk.<br><br>Regards,<br>##logged in user##'
--where EmailTemplateId=66