//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("PMS3_HRMSModel", "FK_Project_Resource_Mapping_ProjectMaster", "ProjectMaster", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(HRMS.DAL.ProjectMaster), "Project_Resource_Mapping", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(HRMS.DAL.Project_Resource_Mapping), true)]
[assembly: EdmRelationshipAttribute("PMS3_HRMSModel", "FK_ProjectMaster_ProjectMaster", "ProjectMaster", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(HRMS.DAL.ProjectMaster), "ProjectMaster1", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(HRMS.DAL.ProjectMaster), true)]

#endregion

namespace HRMS.DAL
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class PMS3_HRMSDBEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new PMS3_HRMSDBEntities object using the connection string found in the 'PMS3_HRMSDBEntities' section of the application configuration file.
        /// </summary>
        public PMS3_HRMSDBEntities() : base("name=PMS3_HRMSDBEntities", "PMS3_HRMSDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new PMS3_HRMSDBEntities object.
        /// </summary>
        public PMS3_HRMSDBEntities(string connectionString) : base(connectionString, "PMS3_HRMSDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new PMS3_HRMSDBEntities object.
        /// </summary>
        public PMS3_HRMSDBEntities(EntityConnection connection) : base(connection, "PMS3_HRMSDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Project_Resource_Mapping> Project_Resource_Mapping
        {
            get
            {
                if ((_Project_Resource_Mapping == null))
                {
                    _Project_Resource_Mapping = base.CreateObjectSet<Project_Resource_Mapping>("Project_Resource_Mapping");
                }
                return _Project_Resource_Mapping;
            }
        }
        private ObjectSet<Project_Resource_Mapping> _Project_Resource_Mapping;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ProjectMaster> ProjectMasters
        {
            get
            {
                if ((_ProjectMasters == null))
                {
                    _ProjectMasters = base.CreateObjectSet<ProjectMaster>("ProjectMasters");
                }
                return _ProjectMasters;
            }
        }
        private ObjectSet<ProjectMaster> _ProjectMasters;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Project_Resource_Mapping EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProject_Resource_Mapping(Project_Resource_Mapping project_Resource_Mapping)
        {
            base.AddObject("Project_Resource_Mapping", project_Resource_Mapping);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ProjectMasters EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProjectMasters(ProjectMaster projectMaster)
        {
            base.AddObject("ProjectMasters", projectMaster);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PMS3_HRMSModel", Name="Project_Resource_Mapping")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Project_Resource_Mapping : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Project_Resource_Mapping object.
        /// </summary>
        /// <param name="project_ResourceID">Initial value of the Project_ResourceID property.</param>
        public static Project_Resource_Mapping CreateProject_Resource_Mapping(global::System.Int64 project_ResourceID)
        {
            Project_Resource_Mapping project_Resource_Mapping = new Project_Resource_Mapping();
            project_Resource_Mapping.Project_ResourceID = project_ResourceID;
            return project_Resource_Mapping;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Project_ResourceID
        {
            get
            {
                return _Project_ResourceID;
            }
            set
            {
                if (_Project_ResourceID != value)
                {
                    OnProject_ResourceIDChanging(value);
                    ReportPropertyChanging("Project_ResourceID");
                    _Project_ResourceID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Project_ResourceID");
                    OnProject_ResourceIDChanged();
                }
            }
        }
        private global::System.Int64 _Project_ResourceID;
        partial void OnProject_ResourceIDChanging(global::System.Int64 value);
        partial void OnProject_ResourceIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> ProjectID
        {
            get
            {
                return _ProjectID;
            }
            set
            {
                OnProjectIDChanging(value);
                ReportPropertyChanging("ProjectID");
                _ProjectID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ProjectID");
                OnProjectIDChanged();
            }
        }
        private Nullable<global::System.Int64> _ProjectID;
        partial void OnProjectIDChanging(Nullable<global::System.Int64> value);
        partial void OnProjectIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> UserID
        {
            get
            {
                return _UserID;
            }
            set
            {
                OnUserIDChanging(value);
                ReportPropertyChanging("UserID");
                _UserID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserID");
                OnUserIDChanged();
            }
        }
        private Nullable<global::System.Int64> _UserID;
        partial void OnUserIDChanging(Nullable<global::System.Int64> value);
        partial void OnUserIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> DesignationID
        {
            get
            {
                return _DesignationID;
            }
            set
            {
                OnDesignationIDChanging(value);
                ReportPropertyChanging("DesignationID");
                _DesignationID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DesignationID");
                OnDesignationIDChanged();
            }
        }
        private Nullable<global::System.Int64> _DesignationID;
        partial void OnDesignationIDChanging(Nullable<global::System.Int64> value);
        partial void OnDesignationIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> StartDate
        {
            get
            {
                return _StartDate;
            }
            set
            {
                OnStartDateChanging(value);
                ReportPropertyChanging("StartDate");
                _StartDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StartDate");
                OnStartDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _StartDate;
        partial void OnStartDateChanging(Nullable<global::System.DateTime> value);
        partial void OnStartDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> EndDate
        {
            get
            {
                return _EndDate;
            }
            set
            {
                OnEndDateChanging(value);
                ReportPropertyChanging("EndDate");
                _EndDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EndDate");
                OnEndDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _EndDate;
        partial void OnEndDateChanging(Nullable<global::System.DateTime> value);
        partial void OnEndDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IsConnected
        {
            get
            {
                return _IsConnected;
            }
            set
            {
                OnIsConnectedChanging(value);
                ReportPropertyChanging("IsConnected");
                _IsConnected = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsConnected");
                OnIsConnectedChanged();
            }
        }
        private Nullable<global::System.Int32> _IsConnected;
        partial void OnIsConnectedChanging(Nullable<global::System.Int32> value);
        partial void OnIsConnectedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> ResourceTypeID
        {
            get
            {
                return _ResourceTypeID;
            }
            set
            {
                OnResourceTypeIDChanging(value);
                ReportPropertyChanging("ResourceTypeID");
                _ResourceTypeID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ResourceTypeID");
                OnResourceTypeIDChanged();
            }
        }
        private Nullable<global::System.Int64> _ResourceTypeID;
        partial void OnResourceTypeIDChanging(Nullable<global::System.Int64> value);
        partial void OnResourceTypeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> AllocatedPercentage
        {
            get
            {
                return _AllocatedPercentage;
            }
            set
            {
                OnAllocatedPercentageChanging(value);
                ReportPropertyChanging("AllocatedPercentage");
                _AllocatedPercentage = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AllocatedPercentage");
                OnAllocatedPercentageChanged();
            }
        }
        private Nullable<global::System.Decimal> _AllocatedPercentage;
        partial void OnAllocatedPercentageChanging(Nullable<global::System.Decimal> value);
        partial void OnAllocatedPercentageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Comments
        {
            get
            {
                return _Comments;
            }
            set
            {
                OnCommentsChanging(value);
                ReportPropertyChanging("Comments");
                _Comments = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Comments");
                OnCommentsChanged();
            }
        }
        private global::System.String _Comments;
        partial void OnCommentsChanging(global::System.String value);
        partial void OnCommentsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> RoleID
        {
            get
            {
                return _RoleID;
            }
            set
            {
                OnRoleIDChanging(value);
                ReportPropertyChanging("RoleID");
                _RoleID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RoleID");
                OnRoleIDChanged();
            }
        }
        private Nullable<global::System.Int32> _RoleID;
        partial void OnRoleIDChanging(Nullable<global::System.Int32> value);
        partial void OnRoleIDChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PMS3_HRMSModel", "FK_Project_Resource_Mapping_ProjectMaster", "ProjectMaster")]
        public ProjectMaster ProjectMaster
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ProjectMaster>("PMS3_HRMSModel.FK_Project_Resource_Mapping_ProjectMaster", "ProjectMaster").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ProjectMaster>("PMS3_HRMSModel.FK_Project_Resource_Mapping_ProjectMaster", "ProjectMaster").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ProjectMaster> ProjectMasterReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ProjectMaster>("PMS3_HRMSModel.FK_Project_Resource_Mapping_ProjectMaster", "ProjectMaster");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ProjectMaster>("PMS3_HRMSModel.FK_Project_Resource_Mapping_ProjectMaster", "ProjectMaster", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PMS3_HRMSModel", Name="ProjectMaster")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ProjectMaster : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ProjectMaster object.
        /// </summary>
        /// <param name="projectID">Initial value of the ProjectID property.</param>
        /// <param name="projectName">Initial value of the ProjectName property.</param>
        /// <param name="projectCode">Initial value of the ProjectCode property.</param>
        /// <param name="isActive">Initial value of the IsActive property.</param>
        public static ProjectMaster CreateProjectMaster(global::System.Int64 projectID, global::System.String projectName, global::System.String projectCode, global::System.Boolean isActive)
        {
            ProjectMaster projectMaster = new ProjectMaster();
            projectMaster.ProjectID = projectID;
            projectMaster.ProjectName = projectName;
            projectMaster.ProjectCode = projectCode;
            projectMaster.IsActive = isActive;
            return projectMaster;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ProjectID
        {
            get
            {
                return _ProjectID;
            }
            set
            {
                if (_ProjectID != value)
                {
                    OnProjectIDChanging(value);
                    ReportPropertyChanging("ProjectID");
                    _ProjectID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ProjectID");
                    OnProjectIDChanged();
                }
            }
        }
        private global::System.Int64 _ProjectID;
        partial void OnProjectIDChanging(global::System.Int64 value);
        partial void OnProjectIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> ProcessID
        {
            get
            {
                return _ProcessID;
            }
            set
            {
                OnProcessIDChanging(value);
                ReportPropertyChanging("ProcessID");
                _ProcessID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ProcessID");
                OnProcessIDChanged();
            }
        }
        private Nullable<global::System.Int64> _ProcessID;
        partial void OnProcessIDChanging(Nullable<global::System.Int64> value);
        partial void OnProcessIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ProjectName
        {
            get
            {
                return _ProjectName;
            }
            set
            {
                OnProjectNameChanging(value);
                ReportPropertyChanging("ProjectName");
                _ProjectName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ProjectName");
                OnProjectNameChanged();
            }
        }
        private global::System.String _ProjectName;
        partial void OnProjectNameChanging(global::System.String value);
        partial void OnProjectNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ProjectCode
        {
            get
            {
                return _ProjectCode;
            }
            set
            {
                OnProjectCodeChanging(value);
                ReportPropertyChanging("ProjectCode");
                _ProjectCode = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ProjectCode");
                OnProjectCodeChanged();
            }
        }
        private global::System.String _ProjectCode;
        partial void OnProjectCodeChanging(global::System.String value);
        partial void OnProjectCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsProjectFixed
        {
            get
            {
                return _IsProjectFixed;
            }
            set
            {
                OnIsProjectFixedChanging(value);
                ReportPropertyChanging("IsProjectFixed");
                _IsProjectFixed = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsProjectFixed");
                OnIsProjectFixedChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsProjectFixed;
        partial void OnIsProjectFixedChanging(Nullable<global::System.Boolean> value);
        partial void OnIsProjectFixedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ProjectStartDate
        {
            get
            {
                return _ProjectStartDate;
            }
            set
            {
                OnProjectStartDateChanging(value);
                ReportPropertyChanging("ProjectStartDate");
                _ProjectStartDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ProjectStartDate");
                OnProjectStartDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _ProjectStartDate;
        partial void OnProjectStartDateChanging(Nullable<global::System.DateTime> value);
        partial void OnProjectStartDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ProjectEndDate
        {
            get
            {
                return _ProjectEndDate;
            }
            set
            {
                OnProjectEndDateChanging(value);
                ReportPropertyChanging("ProjectEndDate");
                _ProjectEndDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ProjectEndDate");
                OnProjectEndDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _ProjectEndDate;
        partial void OnProjectEndDateChanging(Nullable<global::System.DateTime> value);
        partial void OnProjectEndDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsActive
        {
            get
            {
                return _IsActive;
            }
            set
            {
                OnIsActiveChanging(value);
                ReportPropertyChanging("IsActive");
                _IsActive = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsActive");
                OnIsActiveChanged();
            }
        }
        private global::System.Boolean _IsActive;
        partial void OnIsActiveChanging(global::System.Boolean value);
        partial void OnIsActiveChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> DeliveryUnitID
        {
            get
            {
                return _DeliveryUnitID;
            }
            set
            {
                OnDeliveryUnitIDChanging(value);
                ReportPropertyChanging("DeliveryUnitID");
                _DeliveryUnitID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DeliveryUnitID");
                OnDeliveryUnitIDChanged();
            }
        }
        private Nullable<global::System.Int32> _DeliveryUnitID;
        partial void OnDeliveryUnitIDChanging(Nullable<global::System.Int32> value);
        partial void OnDeliveryUnitIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> DeliveryTeamID
        {
            get
            {
                return _DeliveryTeamID;
            }
            set
            {
                OnDeliveryTeamIDChanging(value);
                ReportPropertyChanging("DeliveryTeamID");
                _DeliveryTeamID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DeliveryTeamID");
                OnDeliveryTeamIDChanged();
            }
        }
        private Nullable<global::System.Int32> _DeliveryTeamID;
        partial void OnDeliveryTeamIDChanging(Nullable<global::System.Int32> value);
        partial void OnDeliveryTeamIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> ProjectHours
        {
            get
            {
                return _ProjectHours;
            }
            set
            {
                OnProjectHoursChanging(value);
                ReportPropertyChanging("ProjectHours");
                _ProjectHours = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ProjectHours");
                OnProjectHoursChanged();
            }
        }
        private Nullable<global::System.Double> _ProjectHours;
        partial void OnProjectHoursChanging(Nullable<global::System.Double> value);
        partial void OnProjectHoursChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PMS3_HRMSModel", "FK_Project_Resource_Mapping_ProjectMaster", "Project_Resource_Mapping")]
        public EntityCollection<Project_Resource_Mapping> Project_Resource_Mapping
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Project_Resource_Mapping>("PMS3_HRMSModel.FK_Project_Resource_Mapping_ProjectMaster", "Project_Resource_Mapping");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Project_Resource_Mapping>("PMS3_HRMSModel.FK_Project_Resource_Mapping_ProjectMaster", "Project_Resource_Mapping", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PMS3_HRMSModel", "FK_ProjectMaster_ProjectMaster", "ProjectMaster1")]
        public ProjectMaster ProjectMaster1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ProjectMaster>("PMS3_HRMSModel.FK_ProjectMaster_ProjectMaster", "ProjectMaster1").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ProjectMaster>("PMS3_HRMSModel.FK_ProjectMaster_ProjectMaster", "ProjectMaster1").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ProjectMaster> ProjectMaster1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ProjectMaster>("PMS3_HRMSModel.FK_ProjectMaster_ProjectMaster", "ProjectMaster1");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ProjectMaster>("PMS3_HRMSModel.FK_ProjectMaster_ProjectMaster", "ProjectMaster1", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PMS3_HRMSModel", "FK_ProjectMaster_ProjectMaster", "ProjectMaster")]
        public ProjectMaster ProjectMaster2
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ProjectMaster>("PMS3_HRMSModel.FK_ProjectMaster_ProjectMaster", "ProjectMaster").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ProjectMaster>("PMS3_HRMSModel.FK_ProjectMaster_ProjectMaster", "ProjectMaster").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ProjectMaster> ProjectMaster2Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ProjectMaster>("PMS3_HRMSModel.FK_ProjectMaster_ProjectMaster", "ProjectMaster");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ProjectMaster>("PMS3_HRMSModel.FK_ProjectMaster_ProjectMaster", "ProjectMaster", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
